apiVersion: v1
kind: Service
metadata:
  name: tesior-pkm-service
spec:
  selector:
    app: tesior-pkm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort