version: "3.9"

services:
  api:
    container_name: tesior-pkm
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 1gb
    tty: true
    restart: always
    env_file: .env
    networks:
      - tesior
    ports:
      - "3000:3000"
    volumes:
      - .:/app:rw
    command: ["yarn", "dev"]

networks:
  tesior: {}
